[
  {
    name: {
      common: 'United States Minor Outlying Islands',
      official: 'United States Minor Outlying Islands',
      nativeName: {
        eng: {
          official: 'United States Minor Outlying Islands',
          common: 'United States Minor Outlying Islands',
        },
      },
    },
    tld: ['.us'],
    cca2: 'UM',
    ccn3: '581',
    cca3: 'UMI',
    independent: false,
    status: 'officially-assigned',
    unMember: false,
    currencies: {
      USD: {
        name: 'United States dollar',
        symbol: '$',
      },
    },
    idd: {
      root: '+2',
      suffixes: ['68'],
    },
    capital: ['Washington DC'],
    altSpellings: ['UM'],
    region: 'Americas',
    subregion: 'North America',
    languages: {
      eng: 'English',
    },
    translations: {
      ara: {
        official: 'جزر الولايات المتحدة الصغيرة النائية',
        common: 'جزر الولايات المتحدة الصغيرة النائية',
      },
      bre: {
        official: 'Inizi Minor A-bell Stadoù-Unanet',
        common: 'Inizi Minor A-bell Stadoù-Unanet',
      },
      ces: {
        official: 'Menší odlehlé ostrovy Spojených států amerických',
        common: 'Menší odlehlé ostrovy USA',
      },
      cym: {
        official: 'United States Minor Outlying Islands',
        common: 'United States Minor Outlying Islands',
      },
      deu: {
        official: 'USA, kleinere ausgelagerte Inseln',
        common: 'Kleinere Inselbesitzungen der Vereinigten Staaten',
      },
      est: {
        official: 'Ühendriikide väikesed hajasaared',
        common: 'Ühendriikide hajasaared',
      },
      fin: {
        official: 'Yhdysvaltain asumattomat saaret',
        common: 'Yhdysvaltain asumattomat saaret',
      },
      fra: {
        official: 'Îles mineures éloignées des États-Unis',
        common: 'Îles mineures éloignées des États-Unis',
      },
      hrv: {
        official: 'Mali udaljeni otoci SAD-a',
        common: 'Mali udaljeni otoci SAD-a',
      },
      hun: {
        official: 'Az Amerikai Egyesült Államok lakatlan külbirtokai',
        common: 'Az Amerikai Egyesült Államok lakatlan külbirtokai',
      },
      ita: {
        official: 'Stati Uniti Isole Minori',
        common: "Isole minori esterne degli Stati Uniti d'America",
      },
      jpn: {
        official: 'アメリカ合衆国外諸島',
        common: '合衆国領有小離島',
      },
      kor: {
        official: '미국령 군소 제도',
        common: '미국령 군소 제도',
      },
      nld: {
        official: 'Kleine afgelegen eilanden van de Verenigde Staten',
        common: 'Kleine afgelegen eilanden van de Verenigde Staten',
      },
      per: {
        official: 'جزایر کوچک حاشیه‌ای ایالات متحده آمریکا',
        common: 'جزایر کوچک حاشیه‌ای ایالات متحده آمریکا',
      },
      pol: {
        official: 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych',
        common: 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych',
      },
      por: {
        official: 'Estados Unidos Ilhas Menores Distantes',
        common: 'Ilhas Menores Distantes dos Estados Unidos',
      },
      rus: {
        official: 'Внешние малые острова США',
        common: 'Внешние малые острова США',
      },
      slk: {
        official: 'Menšie odľahlé ostrovy Spjoených štátov',
        common: 'Menšie odľahlé ostrovy USA',
      },
      spa: {
        official: 'Estados Unidos Islas menores alejadas de',
        common: 'Islas Ultramarinas Menores de Estados Unidos',
      },
      srp: {
        official: 'Мала спољна острва Сједињених Америчких Држава',
        common: 'Мала спољна острва Сједињених Америчких Држава',
      },
      swe: {
        official: 'Förenta staternas mindre öar i Oceanien och Västindien',
        common: 'Förenta staternas mindre öar i Oceanien och Västindien',
      },
      tur: {
        official: 'Amerika Birleşik Devletleri Küçük Dış Adaları',
        common: 'Amerika Birleşik Devletleri Küçük Dış Adaları',
      },
      urd: {
        official: 'امریکی چھوٹے بیرونی جزائر',
        common: 'امریکی چھوٹے بیرونی جزائر',
      },
      zho: {
        official: '美国本土外小岛屿',
        common: '美国本土外小岛屿',
      },
    },
    latlng: [19.3, 166.633333],
    landlocked: false,
    area: 34.2,
    demonyms: {
      eng: {
        f: 'American Islander',
        m: 'American Islander',
      },
    },
    flag: '🇺🇲',
    maps: {
      googleMaps: 'https://goo.gl/maps/hZKnrzgeK69dDyPF8',
      openStreetMaps: 'https://www.openstreetmap.org/relation/6430384',
    },
    population: 300,
    car: {
      signs: [''],
      side: 'right',
    },
    timezones: ['UTC-11:00', 'UTC-10:00', 'UTC+12:00'],
    continents: ['Oceania'],
    flags: {
      png: 'https://flagcdn.com/w320/um.png',
      svg: 'https://flagcdn.com/um.svg',
    },
    coatOfArms: {},
    startOfWeek: 'monday',
    capitalInfo: {},
  },
  {
    name: {
      common: 'United States',
      official: 'United States of America',
      nativeName: {
        eng: {
          official: 'United States of America',
          common: 'United States',
        },
      },
    },
    tld: ['.us'],
    cca2: 'US',
    ccn3: '840',
    cca3: 'USA',
    cioc: 'USA',
    independent: true,
    status: 'officially-assigned',
    unMember: true,
    currencies: {
      USD: {
        name: 'United States dollar',
        symbol: '$',
      },
    },
    idd: {
      root: '+1',
      suffixes: [
        '201',
        '202',
        '203',
        '205',
        '206',
        '207',
        '208',
        '209',
        '210',
        '212',
        '213',
        '214',
        '215',
        '216',
        '217',
        '218',
        '219',
        '220',
        '224',
        '225',
        '227',
        '228',
        '229',
        '231',
        '234',
        '239',
        '240',
        '248',
        '251',
        '252',
        '253',
        '254',
        '256',
        '260',
        '262',
        '267',
        '269',
        '270',
        '272',
        '274',
        '276',
        '281',
        '283',
        '301',
        '302',
        '303',
        '304',
        '305',
        '307',
        '308',
        '309',
        '310',
        '312',
        '313',
        '314',
        '315',
        '316',
        '317',
        '318',
        '319',
        '320',
        '321',
        '323',
        '325',
        '327',
        '330',
        '331',
        '334',
        '336',
        '337',
        '339',
        '346',
        '347',
        '351',
        '352',
        '360',
        '361',
        '364',
        '380',
        '385',
        '386',
        '401',
        '402',
        '404',
        '405',
        '406',
        '407',
        '408',
        '409',
        '410',
        '412',
        '413',
        '414',
        '415',
        '417',
        '419',
        '423',
        '424',
        '425',
        '430',
        '432',
        '434',
        '435',
        '440',
        '442',
        '443',
        '447',
        '458',
        '463',
        '464',
        '469',
        '470',
        '475',
        '478',
        '479',
        '480',
        '484',
        '501',
        '502',
        '503',
        '504',
        '505',
        '507',
        '508',
        '509',
        '510',
        '512',
        '513',
        '515',
        '516',
        '517',
        '518',
        '520',
        '530',
        '531',
        '534',
        '539',
        '540',
        '541',
        '551',
        '559',
        '561',
        '562',
        '563',
        '564',
        '567',
        '570',
        '571',
        '573',
        '574',
        '575',
        '580',
        '585',
        '586',
        '601',
        '602',
        '603',
        '605',
        '606',
        '607',
        '608',
        '609',
        '610',
        '612',
        '614',
        '615',
        '616',
        '617',
        '618',
        '619',
        '620',
        '623',
        '626',
        '628',
        '629',
        '630',
        '631',
        '636',
        '641',
        '646',
        '650',
        '651',
        '657',
        '660',
        '661',
        '662',
        '667',
        '669',
        '678',
        '681',
        '682',
        '701',
        '702',
        '703',
        '704',
        '706',
        '707',
        '708',
        '712',
        '713',
        '714',
        '715',
        '716',
        '717',
        '718',
        '719',
        '720',
        '724',
        '725',
        '727',
        '730',
        '731',
        '732',
        '734',
        '737',
        '740',
        '743',
        '747',
        '754',
        '757',
        '760',
        '762',
        '763',
        '765',
        '769',
        '770',
        '772',
        '773',
        '774',
        '775',
        '779',
        '781',
        '785',
        '786',
        '801',
        '802',
        '803',
        '804',
        '805',
        '806',
        '808',
        '810',
        '812',
        '813',
        '814',
        '815',
        '816',
        '817',
        '818',
        '828',
        '830',
        '831',
        '832',
        '843',
        '845',
        '847',
        '848',
        '850',
        '854',
        '856',
        '857',
        '858',
        '859',
        '860',
        '862',
        '863',
        '864',
        '865',
        '870',
        '872',
        '878',
        '901',
        '903',
        '904',
        '906',
        '907',
        '908',
        '909',
        '910',
        '912',
        '913',
        '914',
        '915',
        '916',
        '917',
        '918',
        '919',
        '920',
        '925',
        '928',
        '929',
        '930',
        '931',
        '934',
        '936',
        '937',
        '938',
        '940',
        '941',
        '947',
        '949',
        '951',
        '952',
        '954',
        '956',
        '959',
        '970',
        '971',
        '972',
        '973',
        '975',
        '978',
        '979',
        '980',
        '984',
        '985',
        '989',
      ],
    },
    capital: ['Washington, D.C.'],
    altSpellings: ['US', 'USA', 'United States of America'],
    region: 'Americas',
    subregion: 'North America',
    languages: {
      eng: 'English',
    },
    translations: {
      ara: {
        official: 'الولايات المتحدة الامريكية',
        common: 'الولايات المتحدة',
      },
      bre: {
        official: 'Stadoù-Unanet Amerika',
        common: 'Stadoù-Unanet',
      },
      ces: {
        official: 'Spojené státy americké',
        common: 'Spojené státy',
      },
      cym: {
        official: 'United States of America',
        common: 'United States',
      },
      deu: {
        official: 'Vereinigte Staaten von Amerika',
        common: 'Vereinigte Staaten',
      },
      est: {
        official: 'Ameerika Ühendriigid',
        common: 'Ameerika Ühendriigid',
      },
      fin: {
        official: 'Amerikan yhdysvallat',
        common: 'Yhdysvallat',
      },
      fra: {
        official: "Les états-unis d'Amérique",
        common: 'États-Unis',
      },
      hrv: {
        official: 'Sjedinjene Države Amerike',
        common: 'Sjedinjene Američke Države',
      },
      hun: {
        official: 'Amerikai Egyesült Államok',
        common: 'Amerikai Egyesült Államok',
      },
      ita: {
        official: "Stati Uniti d'America",
        common: "Stati Uniti d'America",
      },
      jpn: {
        official: 'アメリカ合衆国',
        common: 'アメリカ合衆国',
      },
      kor: {
        official: '아메리카 합중국',
        common: '미국',
      },
      nld: {
        official: 'Verenigde Staten van Amerika',
        common: 'Verenigde Staten',
      },
      per: {
        official: 'ایالات متحده آمریکا',
        common: 'ایالات متحده آمریکا',
      },
      pol: {
        official: 'Stany Zjednoczone Ameryki',
        common: 'Stany Zjednoczone',
      },
      por: {
        official: 'Estados Unidos da América',
        common: 'Estados Unidos',
      },
      rus: {
        official: 'Соединенные Штаты Америки',
        common: 'Соединённые Штаты Америки',
      },
      slk: {
        official: 'Spojené štáty Americké',
        common: 'Spojené štáty americké',
      },
      spa: {
        official: 'Estados Unidos de América',
        common: 'Estados Unidos',
      },
      srp: {
        official: 'Сједињене Америчке Државе',
        common: 'Сједињене Америчке Државе',
      },
      swe: {
        official: 'Amerikas förenta stater',
        common: 'USA',
      },
      tur: {
        official: 'Amerika Birleşik Devletleri',
        common: 'Amerika Birleşik Devletleri',
      },
      urd: {
        official: 'ریاستہائے متحدہ امریکا',
        common: 'ریاستہائے متحدہ',
      },
      zho: {
        official: '美利坚合众国',
        common: '美国',
      },
    },
    latlng: [38, -97],
    landlocked: false,
    borders: ['CAN', 'MEX'],
    area: 9372610,
    demonyms: {
      eng: {
        f: 'American',
        m: 'American',
      },
      fra: {
        f: 'Américaine',
        m: 'Américain',
      },
    },
    flag: '🇺🇸',
    maps: {
      googleMaps: 'https://goo.gl/maps/e8M246zY4BSjkjAv6',
      openStreetMaps: 'https://www.openstreetmap.org/relation/148838#map=2/20.6/-85.8',
    },
    population: 329484123,
    gini: {
      2018: 41.4,
    },
    fifa: 'USA',
    car: {
      signs: ['USA'],
      side: 'right',
    },
    timezones: [
      'UTC-12:00',
      'UTC-11:00',
      'UTC-10:00',
      'UTC-09:00',
      'UTC-08:00',
      'UTC-07:00',
      'UTC-06:00',
      'UTC-05:00',
      'UTC-04:00',
      'UTC+10:00',
      'UTC+12:00',
    ],
    continents: ['North America'],
    flags: {
      png: 'https://flagcdn.com/w320/us.png',
      svg: 'https://flagcdn.com/us.svg',
      alt: 'The flag of the United States of America is composed of thirteen equal horizontal bands of red alternating with white. A blue rectangle, bearing fifty small five-pointed white stars arranged in nine rows where rows of six stars alternate with rows of five stars, is superimposed in the canton.',
    },
    coatOfArms: {
      png: 'https://mainfacts.com/media/images/coats_of_arms/us.png',
      svg: 'https://mainfacts.com/media/images/coats_of_arms/us.svg',
    },
    startOfWeek: 'sunday',
    capitalInfo: {
      latlng: [38.89, -77.05],
    },
    postalCode: {
      format: '#####-####',
      regex: '^\\d{5}(-\\d{4})?$',
    },
  },
  {
    name: {
      common: 'United States Virgin Islands',
      official: 'Virgin Islands of the United States',
      nativeName: {
        eng: {
          official: 'Virgin Islands of the United States',
          common: 'United States Virgin Islands',
        },
      },
    },
    tld: ['.vi'],
    cca2: 'VI',
    ccn3: '850',
    cca3: 'VIR',
    cioc: 'ISV',
    independent: false,
    status: 'officially-assigned',
    unMember: false,
    currencies: {
      USD: {
        name: 'United States dollar',
        symbol: '$',
      },
    },
    idd: {
      root: '+1',
      suffixes: ['340'],
    },
    capital: ['Charlotte Amalie'],
    altSpellings: ['VI', 'Virgin Islands, U.S.'],
    region: 'Americas',
    subregion: 'Caribbean',
    languages: {
      eng: 'English',
    },
    translations: {
      ara: {
        official: 'جزر العذراء الامريكية',
        common: 'جزر العذراء الامريكية',
      },
      bre: {
        official: "Inizi Gwerc'h ar Stadoù-Unanet",
        common: "Inizi Gwerc'h ar Stadoù-Unanet",
      },
      ces: {
        official: 'Americké Panenské ostrovy',
        common: 'Americké Panenské ostrovy',
      },
      cym: {
        official: 'Virgin Islands of the United States',
        common: 'United States Virgin Islands',
      },
      deu: {
        official: 'Amerikanische Jungferninseln',
        common: 'Amerikanische Jungferninseln',
      },
      est: {
        official: 'Ühendriikide Neitsisaared',
        common: 'Neitsisaared, USA',
      },
      fin: {
        official: 'Yhdysvaltain Neitsytsaaret',
        common: 'Neitsytsaaret',
      },
      fra: {
        official: 'Îles Vierges des États-Unis',
        common: 'Îles Vierges des États-Unis',
      },
      hrv: {
        official: 'Djevičanski Otoci SAD',
        common: 'Američki Djevičanski Otoci',
      },
      hun: {
        official: 'Amerikai Virgin-szigetek',
        common: 'Amerikai Virgin-szigetek',
      },
      ita: {
        official: 'Isole Vergini degli Stati Uniti',
        common: 'Isole Vergini americane',
      },
      jpn: {
        official: '米国のバージン諸島',
        common: 'アメリカ領ヴァージン諸島',
      },
      kor: {
        official: '미국령 버진아일랜드',
        common: '미국령 버진아일랜드',
      },
      nld: {
        official: 'Maagdeneilanden van de Verenigde Staten',
        common: 'Amerikaanse Maagdeneilanden',
      },
      per: {
        official: 'جزایر ویرجین ایالات متحده آمریکا',
        common: 'جزایر ویرجین ایالات متحده آمریکا',
      },
      pol: {
        official: 'Wyspy Dziewicze Stanów Zjednoczonych',
        common: 'Wyspy Dziewicze Stanów Zjednoczonych',
      },
      por: {
        official: 'Ilhas Virgens dos Estados Unidos',
        common: 'Ilhas Virgens dos Estados Unidos',
      },
      rus: {
        official: 'Виргинские острова Соединенных Штатов',
        common: 'Виргинские Острова',
      },
      slk: {
        official: 'Americké Panenské ostrovy',
        common: 'Americké Panenské ostrovy',
      },
      spa: {
        official: 'Islas Vírgenes de los Estados Unidos',
        common: 'Islas Vírgenes de los Estados Unidos',
      },
      srp: {
        official: 'Америчка Девичанска Острва',
        common: 'Америчка Девичанска Острва',
      },
      swe: {
        official: 'Amerikanska Jungfruöarna',
        common: 'Amerikanska Jungfruöarna',
      },
      tur: {
        official: 'Amerika Birleşik Devletleri Virjin Adaları',
        common: 'ABD Virjin Adaları',
      },
      urd: {
        official: 'امریکی جزائر ورجن',
        common: 'امریکی جزائر ورجن',
      },
      zho: {
        official: '美属维尔京群岛',
        common: '美属维尔京群岛',
      },
    },
    latlng: [18.35, -64.933333],
    landlocked: false,
    area: 347,
    demonyms: {
      eng: {
        f: 'Virgin Islander',
        m: 'Virgin Islander',
      },
    },
    flag: '🇻🇮',
    maps: {
      googleMaps: 'https://goo.gl/maps/mBfreywj8dor6q4m9',
      openStreetMaps: 'openstreetmap.org/relation/286898',
    },
    population: 106290,
    fifa: 'VIR',
    car: {
      signs: ['USA'],
      side: 'right',
    },
    timezones: ['UTC-04:00'],
    continents: ['North America'],
    flags: {
      png: 'https://flagcdn.com/w320/vi.png',
      svg: 'https://flagcdn.com/vi.svg',
    },
    coatOfArms: {},
    startOfWeek: 'monday',
    capitalInfo: {
      latlng: [18.35, -64.93],
    },
  },
];
